# Generated by Django 3.0.6 on 2020-05-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200510_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dare',
            new_name='pub_date',
        ),
    ]
